theme = "solarized-dark"
icons = "material"

[[block]]
block = "music"
max_width = 15
buttons = ["play", "next"]
format = "{combo}"
hide_when_empty = true
marquee_speed = 0.8
marquee_interval = 6

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", api_key = "", city_id = "2988507", units = "metric" }

#[[block]]
#block = "docker"
#interval = 2
#format = "{running}|{images}"

[[block]]
block = "nvidia_gpu"
label = ""
show_utilization = true
show_temperature = true
show_memory = false
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
[block.icons_overrides]
memory_mem="\ue3a5"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
[block.icons_overrides]
thermometer="\ue80e"

[[block]]
block = "cpu"
interval = 1
[block.icons_overrides]
cpu="\ue322"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m} {5m} {15m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%H:%M %d/%m"

[[block]]
block = "battery"

[[block]]
block = "notify"
